apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - image: nonodrama/quotes-data:v1
        name: database
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_PASSWORD
          valueFrom: 
              secretKeyRef:
                name: data-secret
                key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
              secretKeyRef:
                name: data-secret
                key: rootpassword
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: data-secret
              key: username
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: datavp
            subPath: mysql
      volumes:
      - name: datavp
        persistentVolumeClaim:
          claimName: dataclaim
      restartPolicy: Always